all:
	@rm -rf $(ROOTBUILD)/main.exe; 

# 	compiler 
	@$(GCC) $(INC) $(FLAGS) -c tests/tests_main.c -o $(ROOTBUILD)/main.o
	
#	linker
	@$(GCC) $(ROOTBUILD)/main.o \
		$(ROOTBUILD)/tap.o \
		$(ROOTBUILD)/mongoose.o \
		$(LFLAGS) -o \
		$(ROOTBUILD)/main.exe
